### ISSUE TITLE
Game Initialisation

### ISSUE THREAD

**Issue by BastiaanGrisel** [BastiaanGrisel/PrivacyAwarenessGame#11]
Naam invoeren en synchroniseren alle players
Als je op enter drukt, dan moet de data worden verdeeld:
	- Alleen actie als 10 man zijn geconnect
	- Iedereen krijgt een profiel toegewezen en krijgt drie stukjes data uit drie categorieen 
	- Iedereen krijgt drie cheat-tokens 
	- Er worden twee teams gevormd
	- Iedere speler krijgt een route toebedeeld
Iedereen begint in de middelste kamer
Als er een elfde speler wil connecten, dan mag het niet

**Comment by psoffers** [comment]
Hey, this is a description of the use case procedure before the game starts.
[Use Case Number 2 Start of the game.pdf](https://github.com/BastiaanGrisel/PrivacyAwarenessGame/files/59900/Use.Case.Number.2.Start.of.the.game.pdf)

**Comment by IreneDeVreede** [comment]
[Game_Initialisation.pdf](https://github.com/BastiaanGrisel/PrivacyAwarenessGame/files/63940/Game_Initialisation.pdf)
