### ISSUE TITLE
Make doors work with new data

### ISSUE THREAD

**Issue by BastiaanGrisel** [BastiaanGrisel/PrivacyAwarenessGame#14]
Horizontale text met elk een triggerbox
Als ze alle drie zijn ingevuld gaat de deur open
Terug door een deur mag altijd 
Deuren kunnen nog niet gereset worden
Drie verschillende categorien per deur (random?)

**Comment by IreneDeVreede** [comment]
[BSG_Doors_Part1.pdf](https://github.com/BastiaanGrisel/PrivacyAwarenessGame/files/62517/BSG_Doors_Part1.pdf)

**Comment by IreneDeVreede** [comment]
Improved version of the doors use case, 
[DoorsBasic.pdf](https://github.com/BastiaanGrisel/PrivacyAwarenessGame/files/63979/DoorsBasic.pdf)

**Comment by BastiaanGrisel** [comment]
Volgens mij is dit wel klaar, je kan alleen nog niet verkeerde data invoeren.
